MFRRRR build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,10 +13,17 @@ jobs:
         run: |
           brew install autoconf automake libtool pkg-config hidapi libevent qt5 boost gmp
 
-      - name: Set Qt Environment Variables
+      - name: Debug File Existence
         run: |
-          echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> $HOME/.bashrc
-          echo 'export CMAKE_PREFIX_PATH="/usr/local/opt/qt"' >> $HOME/.bashrc
+          ls -R lib/ || echo "Directory lib/ does not exist"
+          ls -R src/ || echo "Directory src/ does not exist"
+          find . -name "univalue_write.cpp" || echo "File not found"
+
+      - name: Clone Univalue (if missing)
+        run: |
+          if [ ! -d "src/univalue" ]; then
+            git clone https://github.com/bitcoin-core/univalue.git src/univalue
+          fi
 
       - name: Run autogen.sh
         run: |
@@ -27,12 +34,11 @@ jobs:
         run: |
           export LDFLAGS="-framework Security -framework CoreServices -framework Foundation -framework ApplicationServices -framework AppKit -framework IOKit"
           ./configure --with-gui=no LDFLAGS="$LDFLAGS"
+          make -j$(sysctl -n hw.ncpu)
 
       - name: Fix `sprintf` Usage
-        run: sed -i '' 's/sprintf/snprintf/g' lib/univalue_write.cpp
-
-      - name: Fix Missing `btc_script_op_new` Prototype
-        run: echo "btc_script_op* btc_script_op_new(void);" >> include/btc/script.h
+        run: |
+          find . -name "univalue_write.cpp" -exec sed -i '' 's/sprintf/snprintf/g' {} +
 
       - name: Compile Code
         run: make -j$(sysctl -n hw.ncpu)
